version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    #privileged: true
    ports:
      - "8125:8080"
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data: