version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: --no-auth
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: