# source that was modified: https://github.com/wurstmeister/kafka-docker 
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.1.51
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # rest proxy stuff:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - local_kafka_data:/var/lib/kafka

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports: 
      - "49092:9000"
    environment:
      APPLICATION_SECRET: letmein
      ZK_HOSTS: zookeeper:2181

  kafka-rest:
    image: nodefluent/kafka-rest
    ports:
      - 8082:8082
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_REST_DEBUG: "all"
      KAFKA_REST_HTTP_PORT: 8082
      KAFKA_REST_CONSUMER_METADATA_BROKER_LIST: "kafka:9092"
      KAFKA_REST_PRODUCER_METADATA_BROKER_LIST: "kafka:9092"

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    ports:
      - 18888:8000
    links:
      - kafka-rest
    depends_on:
      - kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:8082"
      PROXY: "true"

volumes:
  local_kafka_data:
  

